# Generated by Django 4.2.9 on 2026-03-28 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height_cm', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('target_weight', models.FloatField(blank=True, help_text='Target weight in kg', null=True)),
                ('target_steps', models.PositiveIntegerField(default=10000)),
                ('target_calories', models.PositiveIntegerField(default=2000)),
                ('target_sleep_hours', models.FloatField(default=8.0)),
                ('target_water_liters', models.FloatField(default=2.5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
